### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by 263055** [cmdparkour/vue-admin-box#58]
[vite] Internal server error: ENOENT: no such file or directory, scandir 'D:\AJetBriains\Code1\vue-admin-box-3-22-\src\assets\svg'

 at Object.readdirSync (node:fs:1438:3)
      at D:\AJetBriains\Code1\vue-admin-box-3-22-\node_modules\@webxrd\vite-plugin-svg\lib\index.js:33:16
      at Array.forEach (<anonymous>)
      at getAllSvgFileName (D:\AJetBriains\Code1\vue-admin-box-3-22-\node_modules\@webxrd\vite-plugin-svg\lib\index.js:32:14)
      at D:\AJetBriains\Code1\vue-admin-box-3-22-\node_modules\@webxrd\vite-plugin-svg\lib\index.js:115:25
      at Context.load (D:\AJetBriains\Code1\vue-admin-box-3-22-\node_modules\@webxrd\vite-plugin-svg\lib\index.js:204:23)
      at Object.load (D:\AJetBriains\Code1\vue-admin-box-3-22-\node_modules\vite\dist\node\chunks\dep-689425f3.js:39293:50)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async doTransform (D:\AJetBriains\Code1\vue-admin-box-3-22-\node_modules\vite\dist\node\chunks\dep-689425f3.js:49982:24) 
      
      该怎么解决，求大佬救助

**Comment by tipsbefore** [comment]
新建一个svg文件夹吧，应该就能解决这个问题，晚上我处理一下

**Comment by cmdparkour** [comment]
fixed it ,and you can pull it
